# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        /blog/:categories/:year/:month/:day/:title/

# Setup
title:            Poole
tagline:          'The Jekyll Butler'
description:      'Base theme for Jekyll themes by @mdo.'
url:              http://getpoole.com

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         1
paginate_path: 	  "blog/page:num"

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/poole

exclude: 		  ['gruntfile.js', 'package.json', 'LICENSE.md', 'README.md', 'less', 'src']
