# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        /blog/:categories/:year/:month/:day/:title/

# Setup
title:            Villainy
tagline:          'Online nonsense of Warren Haskins' 
description:      'Front and Back end web developer'
url:              http://villainyhq.com

author:
  name:           'Warren Haskins'
  url:            https://twitter.com/warrenhaskins

paginate:         1
paginate_path: 	  "blog/page:num"

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/wurren/wurren.github.io

exclude: 		  ['gruntfile.js', 'package.json', 'LICENSE.md', 'README.md', 'less', 'src']
